In [20]:
# Import Dependencies
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [21]:
# Read in CSV file
csv = Path("..\..\Resources\cleaned_df.csv")
travel_df = pd.read_csv(csv)
travel_df.head()

Duration  Cost of Travel(Entire Trip) in Euros Mode of Travel    Stay  \
0         1                               20111.0         Flight   Hotel   
1         5                               29681.0            Car   Hotel   
2         7                               24950.0         Flight  Airbnb   
3        19                               18676.0       Roadtrip  Airbnb   
4        28                               18899.0         Flight  Airbnb   

  First Name Last Name Date of Birth  \
0   Cristina   Fuentes    1914-06-14   
1   Patricia     Young    1923-09-25   
2  Christina     Kirby    1935-01-02   
3    Michael    Hudson    1982-04-21   
4  Francisco   Hensley    1913-06-29   

                                             Address  Age         Sex  \
0      5143 Pope Camp Apt. 028\nLake Emily, UT 71371   74  Non-Binary   
1  716 Dominguez Row Suite 775\nSouth Tiffanyboro...   19      Female   
2                   PSC 4600, Box 1237\nAPO AE 32510   36      Female   
3   7013 Bryant Club Suite 695\nSouth Tina, WI 26739   38  Non-Binary   
4     074 Scott Brook Suite 700\nLukeville, VA 46541   38  Non-Binary   

                        Nationality Date of Travel  Year  Month  Day  \
0  Lao People's Democratic Republic     2022-09-13  2022      9   13   
1                             Gabon     2021-09-04  2021      9    4   
2              Syrian Arab Republic     2021-01-25  2021      1   25   
3                       Afghanistan     2022-01-28  2022      1   28   
4                           Uruguay     2021-10-21  2021     10   21   

   Cost per Day    ZIP  
0  20111.000000  71371  
1   5936.200000  27800  
2   3564.285714  32510  
3    982.947368  26739  
4    674.964286  46541

In [25]:
# Separate features from target
y = travel_df["Cost of Travel(Entire Trip) in Euros"]
X = travel_df["Month"].values.reshape(-1, 1)

In [26]:
# Split the dataset using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [27]:
# Create logistic regression model.
logistic_regression_model = LogisticRegression(random_state=1)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [28]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [29]:
# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
# Create and save the confusion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [31]:
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

      5021.0       0.00      0.00      0.00         1
      5095.0       0.00      0.00      0.00         1
      5098.0       0.00      0.00      0.00         1
      5131.0       0.00      0.00      0.00         1
      5134.0       0.00      0.00      0.00         1
      5156.0       0.00      0.00      0.00         1
      5157.0       0.00      0.00      0.00         1
      5160.0       0.00      0.00      0.00         1
      5162.0       0.00      0.00      0.00         1
      5175.0       0.00      0.00      0.00         1
      5187.0       0.00      0.00      0.00         1
      5204.0       0.00      0.00      0.00         1
      5224.0       0.00      0.00      0.00         1
      5238.0       0.00      0.00      0.00         1
      5242.0       0.00      0.00      0.00         1
      5256.0       0.00      0.00      0.00         1
      5259.0       0.00      0.00      0.00         2
      5279.0       0.00    

c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
# Create and save the testing classification report
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

      5032.0       0.00      0.00      0.00       1.0
      5037.0       0.00      0.00      0.00       1.0
      5055.0       0.00      0.00      0.00       2.0
      5079.0       0.00      0.00      0.00       1.0
      5098.0       0.00      0.00      0.00       1.0
      5106.0       0.00      0.00      0.00       1.0
      5118.0       0.00      0.00      0.00       1.0
      5133.0       0.00      0.00      0.00       1.0
      5138.0       0.00      0.00      0.00       1.0
      5211.0       0.00      0.00      0.00       1.0
      5228.0       0.00      0.00      0.00       1.0
      5233.0       0.00      0.00      0.00       1.0
      5331.0       0.00      0.00      0.00       1.0
      5353.0       0.00      0.00      0.00       1.0
      5367.0       0.00      0.00      0.00       1.0
      5502.0       0.00      0.00      0.00       1.0
      5560.0       0.00      0.00      0.00       1.0
      5580.0       0.00    

c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dgkau\anaconda3\envs\Python_Data\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dgk